"""Write the paper's numeric appendix tables as LaTeX (paper_latex/tables/*.tex, \\input by acl_latex.tex) and
copy the figures the paper uses into paper_latex/figures/. Every number comes from the pipeline outputs under
<base_out>/paper/ (aggpaper.py, lesions_report.py, manifold_summary, robustness, model_validation).

Usage: python3 -m grok.cli.paper_tables --base-out ./exceptions_runs --tex-dir ./paper_latex
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import pandas as pd

from ..analysis.lesion_summary import load_lesion_tables, mean_over_controls, summary_table, with_deltas
from ..analysis.paper_tables import (grok_steps_table, headline_intervals_table, hidden_progress_table, lesion_table, lowpass_table,
                                     manifold_table, pos_ablation_table, regimes_table, robustness_table, route_order_table,
                                     validation_table)

# figures of the paper: destination name >> source relative to <base_out>/paper (or the project root for fig1/fig2)
FIGURES = {
    "fig1_grokking_phases_schematic.png": "ROOT/fig1_grokking_phases_schematic.png",
    "fig2_cognitive_architecture_map.png": "ROOT/fig2_cognitive_architecture_map.png",
    "regime_shares.png": "regime_shares.png",
    "cognitive_regimes.png": "supp/cognitive_regimes.png",
    "hidden_progress.png": "hidden_progress.png",
    "order_vs_overreg.png": "order_vs_overreg.png",
    "ucurve_add.png": "supp/ucurve_rel_add_rho0.02_wd0.1.png",
    "grok_delay.png": "supp/grok_delay.png",
    "lesion_headline.png": "lesions/lesion_headline.png",
    "lesion_cognitive.png": "lesions/lesion_cognitive.png",
    "lesion_development.png": "lesions/lesion_development.png",
    "grok_order.png": "grok_order.png",
    "item_order_add.png": "supp/item_order_add_rho0_wd0.1.png",
    "manifold_heatmaps.png": "manifolds/manifold_heatmaps.png",
    "atrium_gate.png": "supp/atrium_gate.png",
}


# Entry point that renders the paper's numeric appendix tables as LaTeX and copies the figures the
# paper uses. Every number comes from the pipeline's own outputs under <base_out>/paper/.
# Input: command-line arguments (see the module docstring, which is also the --help text)
# Output: None - writes --tex-dir/tables/*.tex and --tex-dir/figures/
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base-out", type=Path, default=Path("./exceptions_runs"))
    ap.add_argument("--tex-dir", type=Path, default=Path("./paper_latex"))
    ap.add_argument("--no-figures", action="store_true", help="tables only")
    args = ap.parse_args()
    paper = args.base_out / "paper"
    out = args.tex_dir / "tables"
    out.mkdir(parents=True, exist_ok=True)

    tab = pd.read_csv(paper / "runs_table.csv")
    tab["regime_seq"] = tab.regime_seq.fillna("")
    d = load_lesion_tables(args.base_out, "add")
    x = mean_over_controls(with_deltas(d))
    x = x[x.step_req == "final"]
    summ = summary_table(x, "in")
    tables = {
        "grok_steps": grok_steps_table(tab),
        "regimes": regimes_table(tab),
        "hidden_progress": hidden_progress_table(tab),
        "route_order": route_order_table(tab),
        "lesions": lesion_table(x, summ, "in"),
        "lowpass": lowpass_table(pd.read_csv(paper / "lesions" / "lesion_cognitive_table.csv")),
        "manifolds": manifold_table(pd.read_csv(paper / "manifolds" / "manifold_table.csv")),
        "pos_ablation": pos_ablation_table(pd.read_csv(paper / "manifolds" / "pos_ablation.csv")),
        "robustness": robustness_table(pd.read_csv(paper / "supp" / "robustness_sensitivity.csv")),
        "validation": validation_table(pd.read_csv(paper / "supp" / "model_validation.csv")),
        "headline_intervals": headline_intervals_table(pd.read_csv(paper / "supp" / "headline_intervals.csv")),
    }
    for name, tex in tables.items():
        (out / f"{name}.tex").write_text("% generated by python3 -m grok.cli.paper_tables -- do not edit by hand\n" + tex)
        print("wrote", out / f"{name}.tex")

    if not args.no_figures:
        fig_dir = args.tex_dir / "figures"
        fig_dir.mkdir(exist_ok=True)
        for dst, src in FIGURES.items():
            src_path = Path(src.replace("ROOT/", "")) if src.startswith("ROOT/") else paper / src
            if not src_path.exists():
                print("  MISSING figure source:", src_path)
                continue
            shutil.copyfile(src_path, fig_dir / dst)
        print(f"copied {len(FIGURES)} figures to {fig_dir}")


if __name__ == "__main__":
    main()
